In [1]:
import pandas as pd
import numpy as np
import time
import matplotlib.pyplot as plt
from matplotlib.dates import date2num, DayLocator, DateFormatter, MonthLocator

pd.set_option('display.max_rows', 200)
%matplotlib inline

In [25]:
#initialize google map API
from geopy import geocoders

In [26]:
g = geocoders.GoogleV3("AIzaSyCqTMWCA9KPXuNoBfNsd6e2UiMkOgavPDY")

In [27]:
g.geocode("Spain")

Location(Spain, (40.46366700000001, -3.74922, 0.0))

In [3]:
dataL=pd.read_csv('dataAverage.csv')

/Users/shu/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2698: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [4]:
dataL.head(2)

   Latitude  Longitude  LimitingMag                   Country Unnamed: 4
0   42.2301   -89.0416            5  United States - Illinois        NaN
1   51.7887     6.0575            4                   Germany        NaN

In [7]:
dataL.groupby(['Country']).LimitingMag.mean()

Country
Afghanistan                               5.461538
Aland Islands                             7.000000
Albania                                   4.200000
Algeria                                   3.435714
Andorra                                   2.000000
Angola                                    3.500000
Antarctica                                3.478261
Argentina                                 3.209662
Armenia                                   1.000000
Aruba                                     4.333333
Australia                                -0.117647
Austria                                  -8.367033
Azerbaijan                                4.500000
Bahrain                                   3.290323
Bangladesh                             -196.800000
Barbados                                  4.000000
Belarus                                   5.000000
Belgium                                  -1.501894
Belize                                    4.400000
Benin                                     3.333333
Bermuda                                   4.333333
Bhutan                                    2.666667
Bolivia                                   3.500000
Bosnia and Herzegovina                    4.500000
Botswana                                  4.000000
Brazil                                   -6.879310
British Indian Ocean Territory            3.000000
British Virgin Islands                    5.000000
Brunei                                    2.000000
Bulgaria                                  3.445122
Burkina Faso                              3.500000
Cambodia                                  4.400000
Cameroon                                  3.294118
Canada                                   -1.408700
Caribbean Netherlands                     4.000000
Cayman Islands                            4.600000
Central African Republic                  4.500000
Chad                                      4.103448
Chile                                     3.555391
China                                    -8.645103
Colombia                                 -6.560250
Cook Islands                              2.000000
Costa Rica                                4.487047
Croatia                                   2.923750
Cte d'Ivoire                              3.400000
Cuba                                      4.384615
Curaao                                    5.333333
Cyprus                                    4.564103
Czech Republic                            3.731721
Czechia                                   3.696429
Democratic Republic of the Congo          2.000000
Denmark                                 -39.975806
Dominican Republic                        2.666667
Ecuador                                   5.043478
Egypt                                     4.212121
El Salvador                               4.206897
Eritrea                                   2.000000
Estonia                                   3.686567
Ethiopia                                  3.500000
Fiji                                      6.000000
Finland                                   4.144250
France                                  -21.902169
French Polynesia                          3.000000
Georgia                                   2.500000
Germany                                   2.088418
Ghana                                     3.275862
Gibraltar                                 6.000000
Greece                                    4.000000
Greenland                                 3.625000
Guam                                      3.888889
Guatemala                                 3.450331
Guernsey                                  7.000000
Guinea                                    4.666667
Haiti                                     4.000000
Honduras                                  3.902439
Hong Kong                               -16.432692
Hungary                                   4.141264
Iceland                                   4.300000
India                                   -13.918745
Indonesia                               -13.689655
Iran                                    -29.120879
Iraq                                      4.400000
Ireland                                 -36.240876
Isle of Man                               5.290323
Israel                                   -9.421053
Italy                                    -6.708180
Jamaica                                   4.857143
Japan                                     1.513821
Jordan                                    4.200000
Kazakhstan                                3.607143
Kenya                                     1.545455
Kingdom of Norway                         4.333333
Kuwait                                    3.200000
Kyrgyzstan                                3.033333
Laos                                   -246.250000
Latvia                                  -10.428571
Lebanon                                 -64.066667
Liberia                                   3.250000
Libya                                     5.000000
Liechtenstein                             6.000000
                                           ...
Portugal                                  1.213368
Puerto Rico                               1.723942
Qatar                                     3.150000
Republic of Kosovo                        4.000000
Republic of the Congo                     2.000000
Republic of the Union of Myanmar          4.333333
Reunion                                   3.428571
Romania                                   1.398872
Russia                                  -15.638095
Saint Lucia                               3.200000
Saudi Arabia                              3.238095
Senegal                                   3.200000
Serbia                                    3.482353
Singapore                                 3.027027
Slovakia                                  1.249322
Slovenia                                  4.220513
Somalia                                   3.250000
South Africa                              0.900787
South Korea                               1.844328
South Sudan                               4.000000
Spain                                     2.135711
Sri Lanka                                 3.781250
Sudan                                   -80.250000
Sweden                                  -20.817330
Switzerland                              -4.190751
Syria                                     4.666667
Taiwan                                   -8.247863
Tanzania                                  4.466667
Thailand                                 -2.962882
The Bahamas                               4.833333
The Netherlands                         -31.148479
Trinidad and Tobago                       3.764706
Tunisia                                   4.000000
Turkey                                    1.677215
U.S. Virgin Islands                       4.000000
Uganda                                    5.500000
Ukraine                                   3.267327
United Arab Emirates                    -16.708333
United Kingdom                           -9.903065
United States                             3.500000
United States -                           3.636364
United States - Alabama                  -1.165049
United States - Alaska                   -0.120968
United States - Arizona                   3.028626
United States - Arkansas                  2.672152
United States - California               -0.206079
United States - Colorado                  1.794800
United States - Connecticut              -2.335355
United States - Delaware                 -1.526549
United States - District of Columbia    -21.604938
United States - Florida                  -2.161585
United States - Georgia                  -6.929656
United States - Hawaii                    4.307018
United States - Idaho                    -3.774059
United States - Illinois                 -5.104091
United States - Indiana                   2.855005
United States - Iowa                      2.127119
United States - Kansas                    2.099567
United States - Kentucky                  3.903571
United States - Louisiana                 0.082746
United States - Maine                     4.247202
United States - Maryland                 -0.876812
United States - Massachusetts             1.911961
United States - Michigan                -12.862856
United States - Minnesota                 1.067332
United States - Mississippi              -6.923077
United States - Missouri                  1.279851
United States - Montana                   4.537415
United States - Nebraska                -17.373684
United States - Nevada                    3.703579
United States - New Hampshire             2.599707
United States - New Jersey               -1.740399
United States - New Mexico                0.802734
United States - New York                 -2.611872
United States - North Carolina           -1.819594
United States - North Dakota              3.833333
United States - Ohio                      0.250458
United States - Oklahoma                  2.864413
United States - Oregon                    2.456209
United States - Pennsylvania             -1.928891
United States - Rhode Island            -39.478261
United States - South Carolina            1.444779
United States - South Dakota              4.634615
United States - Tennessee                 0.176976
United States - Texas                     0.009980
United States - Utah                    -63.690678
United States - Vermont                   4.562500
United States - Virginia                  1.542810
United States - Washington               -5.794521
United States - West Virginia             3.352201
United States - Wisconsin                 2.862605
United States - Wyoming                  -5.336634
Uruguay                                   3.216003
Uzbekistan                                4.333333
Venezuela                                 3.160714
Vietnam                                -170.211538
Yemen                                     3.625000
Zambia                                    4.333333
Zimbabwe                                  5.250000
timezone: CST                             2.500000
Name: LimitingMag, Length: 236, dtype: float64

In [70]:
dataDes=dataL.groupby('Country')['LimitingMag'].describe()

#                          limitingMag.summary()df.groupby('Category')['Score'].describe()

In [75]:
dataDes1=dataL.groupby('Country').describe()

In [80]:
countryList=dataDes1.index.tolist()

In [84]:
len(countryList)

236

In [71]:
dataDes.head(3)

               count      mean       std  min  25%  50%  75%  max
Country
Afghanistan     13.0  5.461538  0.967418  4.0  5.0  5.0  6.0  7.0
Aland Islands    1.0  7.000000       NaN  7.0  7.0  7.0  7.0  7.0
Albania          5.0  4.200000  2.049390  2.0  2.0  5.0  6.0  6.0

In [72]:
type(dataDes)

pandas.core.frame.DataFrame

In [74]:
dataDes.head(0)

Empty DataFrame
Columns: [count, mean, std, min, 25%, 50%, 75%, max]
Index: []

In [89]:
#here we use median to eliminate the effect of the extreme value
dataDes=dataDes['50%']

In [105]:
dataDes.tail(4)

Country
Yemen            3.5
Zambia           4.0
Zimbabwe         6.0
timezone: CST    2.5
Name: 50%, dtype: float64

In [92]:
magList=dataDes.tolist()

In [111]:
#print out all the processed light data as target format, exported to js file
for i in range(0,235):
                  placemark = g.geocode(countryList[i])
                  print ('{lat:',placemark[1][0],', lng:',placemark[1][1],',','label:"',
                         countryList[i],magList[i],'"}',',')

{lat: 33.93911 , lng: 67.709953 , label:" Afghanistan 5.0 "} ,
{lat: 60.1785247 , lng: 19.9156105 , label:" Aland Islands 7.0 "} ,
{lat: 41.153332 , lng: 20.168331 , label:" Albania 5.0 "} ,
{lat: 28.033886 , lng: 1.659626 , label:" Algeria 4.0 "} ,
{lat: 42.506285 , lng: 1.521801 , label:" Andorra 2.0 "} ,
{lat: -11.202692 , lng: 17.873887 , label:" Angola 3.5 "} ,
{lat: -82.862752 , lng: 135.0 , label:" Antarctica 3.0 "} ,
{lat: -38.416097 , lng: -63.61667199999999 , label:" Argentina 4.0 "} ,
{lat: 40.069099 , lng: 45.038189 , label:" Armenia 1.0 "} ,
{lat: 12.52111 , lng: -69.968338 , label:" Aruba 5.0 "} ,
{lat: -25.274398 , lng: 133.775136 , label:" Australia 4.0 "} ,
{lat: 47.516231 , lng: 14.550072 , label:" Austria 5.0 "} ,
{lat: 40.143105 , lng: 47.576927 , label:" Azerbaijan 4.5 "} ,
{lat: 26.0667 , lng: 50.5577 , label:" Bahrain 3.0 "} ,
{lat: 23.684994 , lng: 90.356331 , label:" Bangladesh 3.0 "} ,
{lat: 13.193887 , lng: -59.543198 , label:" Barbados 4.0 "} ,
{lat: 53.709807 , lng: 27.953389 , label:" Belarus 5.0 "} ,
{lat: 50.503887 , lng: 4.469936 , label:" Belgium 4.0 "} ,
{lat: 17.189877 , lng: -88.49765 , label:" Belize 4.0 "} ,
{lat: 9.30769 , lng: 2.315834 , label:" Benin 3.0 "} ,
{lat: 32.3078 , lng: -64.7505 , label:" Bermuda 4.0 "} ,
{lat: 27.514162 , lng: 90.433601 , label:" Bhutan 3.0 "} ,
{lat: -16.290154 , lng: -63.58865299999999 , label:" Bolivia 3.0 "} ,
{lat: 43.915886 , lng: 17.679076 , label:" Bosnia and Herzegovina 5.0 "} ,
{lat: -22.328474 , lng: 24.684866 , label:" Botswana 3.5 "} ,
{lat: -14.235004 , lng: -51.92528 , label:" Brazil 4.0 "} ,
{lat: -6.343194 , lng: 71.876519 , label:" British Indian Ocean Territory 3.0 "} ,
{lat: 18.420695 , lng: -64.639968 , label:" British Virgin Islands 5.0 "} ,
{lat: 4.535277 , lng: 114.727669 , label:" Brunei 2.0 "} ,
{lat: 42.733883 , lng: 25.48583 , label:" Bulgaria 4.0 "} ,
{lat: 12.238333 , lng: -1.561593 , label:" Burkina Faso 3.0 "} ,
{lat: 12.565679 , lng: 104.990963 , label:" Cambodia 5.0 "} ,
{lat: 7.369721999999999 , lng: 12.354722 , label:" Cameroon 4.0 "} ,
{lat: 56.130366 , lng: -106.346771 , label:" Canada 4.0 "} ,
{lat: 12.1783611 , lng: -68.2385339 , label:" Caribbean Netherlands 4.0 "} ,
{lat: 19.3133 , lng: -81.2546 , label:" Cayman Islands 5.0 "} ,
{lat: 6.611110999999999 , lng: 20.939444 , label:" Central African Republic 4.5 "} ,
{lat: 15.454166 , lng: 18.732207 , label:" Chad 4.0 "} ,
{lat: -35.675147 , lng: -71.542969 , label:" Chile 4.0 "} ,
{lat: 35.86166 , lng: 104.195397 , label:" China 3.0 "} ,
{lat: 4.570868 , lng: -74.297333 , label:" Colombia 3.0 "} ,
{lat: -21.236736 , lng: -159.777671 , label:" Cook Islands 2.0 "} ,
{lat: 9.748916999999999 , lng: -83.753428 , label:" Costa Rica 4.0 "} ,
{lat: 45.1 , lng: 15.2000001 , label:" Croatia 3.0 "} ,
{lat: 7.539988999999999 , lng: -5.547079999999999 , label:" Cte d'Ivoire 4.0 "} ,
{lat: 21.521757 , lng: -77.781167 , label:" Cuba 5.0 "} ,
{lat: 12.16957 , lng: -68.99002 , label:" Curaao 6.0 "} ,
{lat: 35.126413 , lng: 33.429859 , label:" Cyprus 5.0 "} ,
{lat: 49.81749199999999 , lng: 15.472962 , label:" Czech Republic 4.0 "} ,
{lat: 49.81749199999999 , lng: 15.472962 , label:" Czechia 3.5 "} ,
{lat: -4.038333 , lng: 21.758664 , label:" Democratic Republic of the Congo 2.0 "} ,
{lat: 56.26392 , lng: 9.501785 , label:" Denmark 5.0 "} ,
{lat: 18.735693 , lng: -70.162651 , label:" Dominican Republic 3.0 "} ,
{lat: -1.831239 , lng: -78.18340599999999 , label:" Ecuador 5.0 "} ,
{lat: 26.820553 , lng: 30.802498 , label:" Egypt 5.0 "} ,
{lat: 13.794185 , lng: -88.89653 , label:" El Salvador 4.0 "} ,
{lat: 15.179384 , lng: 39.782334 , label:" Eritrea 2.0 "} ,
{lat: 58.595272 , lng: 25.0136071 , label:" Estonia 4.0 "} ,
{lat: 9.145000000000001 , lng: 40.489673 , label:" Ethiopia 3.5 "} ,
{lat: -17.713371 , lng: 178.065032 , label:" Fiji 6.0 "} ,
{lat: 61.92410999999999 , lng: 25.7481511 , label:" Finland 4.0 "} ,
{lat: 46.227638 , lng: 2.213749 , label:" France 5.0 "} ,
{lat: -17.679742 , lng: -149.406843 , label:" French Polynesia 3.0 "} ,
{lat: 32.1656221 , lng: -82.9000751 , label:" Georgia 2.5 "} ,
{lat: 51.165691 , lng: 10.451526 , label:" Germany 5.0 "} ,
{lat: 7.946527 , lng: -1.023194 , label:" Ghana 3.0 "} ,
{lat: 36.140751 , lng: -5.353585 , label:" Gibraltar 6.0 "} ,
{lat: 39.074208 , lng: 21.824312 , label:" Greece 4.0 "} ,
{lat: 71.706936 , lng: -42.604303 , label:" Greenland 4.0 "} ,
{lat: 13.444304 , lng: 144.793731 , label:" Guam 4.0 "} ,
{lat: 15.783471 , lng: -90.23075899999999 , label:" Guatemala 4.0 "} ,
{lat: 49.465691 , lng: -2.585278 , label:" Guernsey 7.0 "} ,
{lat: 9.945587 , lng: -9.696645 , label:" Guinea 4.0 "} ,
{lat: 18.971187 , lng: -72.285215 , label:" Haiti 4.0 "} ,
{lat: 15.199999 , lng: -86.241905 , label:" Honduras 4.0 "} ,
{lat: 22.396428 , lng: 114.109497 , label:" Hong Kong 3.0 "} ,
{lat: 47.162494 , lng: 19.5033041 , label:" Hungary 4.0 "} ,
{lat: 64.963051 , lng: -19.020835 , label:" Iceland 3.5 "} ,
{lat: 20.593684 , lng: 78.96288 , label:" India 3.0 "} ,
{lat: -0.789275 , lng: 113.921327 , label:" Indonesia 3.0 "} ,
{lat: 32.427908 , lng: 53.688046 , label:" Iran 4.0 "} ,
{lat: 33.223191 , lng: 43.679291 , label:" Iraq 4.0 "} ,
{lat: 53.1423672 , lng: -7.692053599999999 , label:" Ireland 4.0 "} ,
{lat: 54.236107 , lng: -4.548056 , label:" Isle of Man 5.0 "} ,
{lat: 31.046051 , lng: 34.851612 , label:" Israel 4.0 "} ,
{lat: 41.87194 , lng: 12.56738 , label:" Italy 4.0 "} ,
{lat: 18.109581 , lng: -77.297508 , label:" Jamaica 5.0 "} ,
{lat: 36.204824 , lng: 138.252924 , label:" Japan 3.0 "} ,
{lat: 30.585164 , lng: 36.238414 , label:" Jordan 4.0 "} ,
{lat: 48.019573 , lng: 66.923684 , label:" Kazakhstan 3.5 "} ,
{lat: -0.023559 , lng: 37.906193 , label:" Kenya 1.0 "} ,
{lat: 60.47202399999999 , lng: 8.468945999999999 , label:" Kingdom of Norway 4.0 "} ,
{lat: 29.31166 , lng: 47.481766 , label:" Kuwait 2.5 "} ,
{lat: 41.20438 , lng: 74.766098 , label:" Kyrgyzstan 3.0 "} ,
{lat: 19.85627 , lng: 102.495496 , label:" Laos 4.5 "} ,
{lat: 56.879635 , lng: 24.603189 , label:" Latvia 4.0 "} ,
{lat: 33.854721 , lng: 35.862285 , label:" Lebanon 3.0 "} ,
{lat: 6.428055 , lng: -9.429499000000002 , label:" Liberia 3.5 "} ,
{lat: 26.3351 , lng: 17.228331 , label:" Libya 5.0 "} ,
{lat: 47.166 , lng: 9.555373 , label:" Liechtenstein 6.0 "} ,
{lat: 55.169438 , lng: 23.881275 , label:" Lithuania 4.0 "} ,
{lat: 49.815273 , lng: 6.129582999999999 , label:" Luxembourg 3.0 "} ,
{lat: 22.198745 , lng: 113.543873 , label:" Macau 4.0 "} ,
{lat: 41.608635 , lng: 21.745275 , label:" Macedonia (FYROM) 4.0 "} ,
{lat: -18.766947 , lng: 46.869107 , label:" Madagascar 7.0 "} ,
{lat: 4.210484 , lng: 101.975766 , label:" Malaysia 4.0 "} ,
{lat: 3.202778 , lng: 73.22068 , label:" Maldives 4.5 "} ,
{lat: 17.570692 , lng: -3.996166 , label:" Mali 6.0 "} ,
{lat: 35.937496 , lng: 14.375416 , label:" Malta 4.0 "} ,
{lat: 7.131474 , lng: 171.184478 , label:" Marshall Islands 3.0 "} ,
{lat: 14.641528 , lng: -61.024174 , label:" Martinique 5.0 "} ,
{lat: 21.00789 , lng: -10.940835 , label:" Mauritania 3.0 "} ,
{lat: -20.348404 , lng: 57.55215200000001 , label:" Mauritius 4.0 "} ,
{lat: 23.634501 , lng: -102.552784 , label:" Mexico 4.0 "} ,
{lat: 47.411631 , lng: 28.369885 , label:" Moldova 2.0 "} ,
{lat: 46.862496 , lng: 103.846656 , label:" Mongolia 1.5 "} ,
{lat: 31.791702 , lng: -7.092619999999999 , label:" Morocco 3.0 "} ,
{lat: -18.665695 , lng: 35.529562 , label:" Mozambique 1.0 "} ,
{lat: 21.916221 , lng: 95.955974 , label:" Myanmar (Burma) 6.0 "} ,
{lat: -22.95764 , lng: 18.49041 , label:" Namibia 4.0 "} ,
{lat: 28.394857 , lng: 84.12400799999999 , label:" Nepal 4.0 "} ,
{lat: 52.132633 , lng: 5.291265999999999 , label:" Netherlands 5.0 "} ,
{lat: -20.904305 , lng: 165.618042 , label:" New Caledonia 3.5 "} ,
{lat: -40.900557 , lng: 174.885971 , label:" New Zealand 5.0 "} ,
{lat: 12.865416 , lng: -85.207229 , label:" Nicaragua 4.0 "} ,
{lat: 17.607789 , lng: 8.081666 , label:" Niger 5.0 "} ,
{lat: 9.081999 , lng: 8.675277 , label:" Nigeria 3.0 "} ,
{lat: 40.339852 , lng: 127.510093 , label:" North Korea 1.0 "} ,
{lat: 60.47202399999999 , lng: 8.468945999999999 , label:" Norway 4.0 "} ,

{lat: 21.4735329 , lng: 55.975413 , label:" Oman 3.0 "} ,
{lat: 30.375321 , lng: 69.34511599999999 , label:" Pakistan 4.0 "} ,
{lat: 8.537981 , lng: -80.782127 , label:" Panama 4.0 "} ,
{lat: -23.442503 , lng: -58.443832 , label:" Paraguay 4.0 "} ,
{lat: -9.189967 , lng: -75.015152 , label:" Peru 3.0 "} ,
{lat: 12.879721 , lng: 121.774017 , label:" Philippines 4.0 "} ,
{lat: 51.919438 , lng: 19.145136 , label:" Poland 4.0 "} ,
{lat: 39.39987199999999 , lng: -8.224454 , label:" Portugal 4.0 "} ,
{lat: 18.220833 , lng: -66.590149 , label:" Puerto Rico 3.0 "} ,
{lat: 25.354826 , lng: 51.183884 , label:" Qatar 3.0 "} ,
{lat: 42.6026359 , lng: 20.902977 , label:" Republic of Kosovo 4.0 "} ,
{lat: -0.228021 , lng: 15.827659 , label:" Republic of the Congo 2.0 "} ,
{lat: 21.916221 , lng: 95.955974 , label:" Republic of the Union of Myanmar 4.0 "} ,
{lat: -21.115141 , lng: 55.536384 , label:" Reunion 3.0 "} ,
{lat: 45.943161 , lng: 24.96676 , label:" Romania 4.0 "} ,
{lat: 61.52401 , lng: 105.318756 , label:" Russia 3.0 "} ,
{lat: 13.909444 , lng: -60.978893 , label:" Saint Lucia 4.0 "} ,
{lat: 23.885942 , lng: 45.079162 , label:" Saudi Arabia 3.0 "} ,
{lat: 14.497401 , lng: -14.452362 , label:" Senegal 3.0 "} ,
{lat: 44.016521 , lng: 21.005859 , label:" Serbia 4.0 "} ,
{lat: 1.352083 , lng: 103.819836 , label:" Singapore 3.0 "} ,
{lat: 48.669026 , lng: 19.699024 , label:" Slovakia 4.0 "} ,
{lat: 46.151241 , lng: 14.995463 , label:" Slovenia 4.0 "} ,
{lat: 5.152149 , lng: 46.199616 , label:" Somalia 3.5 "} ,
{lat: -30.559482 , lng: 22.937506 , label:" South Africa 4.0 "} ,
{lat: 35.907757 , lng: 127.766922 , label:" South Korea 3.0 "} ,
{lat: 6.876991899999999 , lng: 31.3069788 , label:" South Sudan 4.0 "} ,
{lat: 40.46366700000001 , lng: -3.74922 , label:" Spain 4.0 "} ,
{lat: 7.873053999999999 , lng: 80.77179699999999 , label:" Sri Lanka 4.0 "} ,
{lat: 12.862807 , lng: 30.217636 , label:" Sudan 4.0 "} ,
{lat: 60.12816100000001 , lng: 18.643501 , label:" Sweden 6.0 "} ,
{lat: 46.818188 , lng: 8.227511999999999 , label:" Switzerland 5.0 "} ,
{lat: 34.80207499999999 , lng: 38.996815 , label:" Syria 6.0 "} ,
{lat: 23.69781 , lng: 120.960515 , label:" Taiwan 3.0 "} ,
{lat: -6.369028 , lng: 34.888822 , label:" Tanzania 4.0 "} ,
{lat: 15.870032 , lng: 100.992541 , label:" Thailand 4.0 "} ,
{lat: 25.03428 , lng: -77.39627999999999 , label:" The Bahamas 4.5 "} ,
{lat: 52.132633 , lng: 5.291265999999999 , label:" The Netherlands 5.0 "} ,
{lat: 10.691803 , lng: -61.222503 , label:" Trinidad and Tobago 4.0 "} ,
{lat: 33.886917 , lng: 9.537499 , label:" Tunisia 4.0 "} ,
{lat: 38.963745 , lng: 35.243322 , label:" Turkey 4.0 "} ,
{lat: 18.335765 , lng: -64.896335 , label:" U.S. Virgin Islands 4.0 "} ,
{lat: 1.373333 , lng: 32.290275 , label:" Uganda 5.5 "} ,
{lat: 48.379433 , lng: 31.1655799 , label:" Ukraine 3.0 "} ,
{lat: 23.424076 , lng: 53.847818 , label:" United Arab Emirates 4.0 "} ,
{lat: 55.378051 , lng: -3.435973 , label:" United Kingdom 4.0 "} ,
{lat: 37.09024 , lng: -95.712891 , label:" United States 3.0 "} ,
{lat: 37.09024 , lng: -95.712891 , label:" United States -  3.0 "} ,
{lat: 32.3182314 , lng: -86.902298 , label:" United States - Alabama 4.0 "} ,
{lat: 64.2008413 , lng: -149.4936733 , label:" United States - Alaska 4.0 "} ,
{lat: 34.0489281 , lng: -111.0937311 , label:" United States - Arizona 4.0 "} ,
{lat: 35.20105 , lng: -91.8318334 , label:" United States - Arkansas 4.0 "} ,
{lat: 36.778261 , lng: -119.4179324 , label:" United States - California 4.0 "} ,
{lat: 39.5500507 , lng: -105.7820674 , label:" United States - Colorado 4.0 "} ,
{lat: 41.6032207 , lng: -73.087749 , label:" United States - Connecticut 4.0 "} ,
{lat: 38.9108325 , lng: -75.52766989999999 , label:" United States - Delaware 3.0 "} ,
{lat: 38.9071923 , lng: -77.0368707 , label:" United States - District of Columbia 3.0 "} ,
{lat: 27.6648274 , lng: -81.5157535 , label:" United States - Florida 4.0 "} ,
{lat: 32.1656221 , lng: -82.9000751 , label:" United States - Georgia 3.0 "} ,
{lat: 19.8967662 , lng: -155.5827818 , label:" United States - Hawaii 4.0 "} ,
{lat: 44.0682019 , lng: -114.7420408 , label:" United States - Idaho 5.0 "} ,
{lat: 40.6331249 , lng: -89.3985283 , label:" United States - Illinois 3.0 "} ,
{lat: 40.2671941 , lng: -86.1349019 , label:" United States - Indiana 4.0 "} ,
{lat: 41.8780025 , lng: -93.097702 , label:" United States - Iowa 4.0 "} ,
{lat: 39.011902 , lng: -98.4842465 , label:" United States - Kansas 4.0 "} ,
{lat: 37.8393332 , lng: -84.2700179 , label:" United States - Kentucky 4.0 "} ,
{lat: 30.9842977 , lng: -91.96233269999999 , label:" United States - Louisiana 4.0 "} ,
{lat: 45.253783 , lng: -69.4454689 , label:" United States - Maine 4.0 "} ,
{lat: 39.0457549 , lng: -76.64127119999999 , label:" United States - Maryland 4.0 "} ,
{lat: 42.4072107 , lng: -71.3824374 , label:" United States - Massachusetts 4.0 "} ,
{lat: 44.3148443 , lng: -85.60236429999999 , label:" United States - Michigan 3.0 "} ,
{lat: 46.729553 , lng: -94.6858998 , label:" United States - Minnesota 4.0 "} ,
{lat: 32.3546679 , lng: -89.3985283 , label:" United States - Mississippi 4.0 "} ,
{lat: 37.9642529 , lng: -91.8318334 , label:" United States - Missouri 4.0 "} ,
{lat: 46.8796822 , lng: -110.3625658 , label:" United States - Montana 4.0 "} ,
{lat: 41.4925374 , lng: -99.9018131 , label:" United States - Nebraska 4.0 "} ,
{lat: 38.8026097 , lng: -116.419389 , label:" United States - Nevada 4.0 "} ,
{lat: 43.1938516 , lng: -71.5723953 , label:" United States - New Hampshire 4.0 "} ,
{lat: 40.0583238 , lng: -74.4056612 , label:" United States - New Jersey 4.0 "} ,
{lat: 34.5199402 , lng: -105.8700901 , label:" United States - New Mexico 5.0 "} ,
{lat: 40.7127753 , lng: -74.0059728 , label:" United States - New York 3.0 "} ,
{lat: 35.7595731 , lng: -79.01929969999999 , label:" United States - North Carolina 4.0 "} ,
{lat: 47.5514926 , lng: -101.0020119 , label:" United States - North Dakota 4.0 "} ,
{lat: 40.4172871 , lng: -82.90712300000001 , label:" United States - Ohio 4.0 "} ,
{lat: 35.0077519 , lng: -97.092877 , label:" United States - Oklahoma 4.0 "} ,
{lat: 43.8041334 , lng: -120.5542012 , label:" United States - Oregon 4.0 "} ,
{lat: 41.2033216 , lng: -77.1945247 , label:" United States - Pennsylvania 4.0 "} ,
{lat: 41.5800945 , lng: -71.4774291 , label:" United States - Rhode Island 4.0 "} ,
{lat: 33.836081 , lng: -81.1637245 , label:" United States - South Carolina 4.0 "} ,
{lat: 43.9695148 , lng: -99.9018131 , label:" United States - South Dakota 5.0 "} ,
{lat: 35.5174913 , lng: -86.5804473 , label:" United States - Tennessee 4.0 "} ,
{lat: 31.9685988 , lng: -99.9018131 , label:" United States - Texas 3.0 "} ,
{lat: 39.3209801 , lng: -111.0937311 , label:" United States - Utah 4.0 "} ,
{lat: 44.5588028 , lng: -72.57784149999999 , label:" United States - Vermont 5.0 "} ,
{lat: 37.4315734 , lng: -78.6568942 , label:" United States - Virginia 4.0 "} ,
{lat: 47.7510741 , lng: -120.7401385 , label:" United States - Washington 4.0 "} ,
{lat: 38.5976262 , lng: -80.4549026 , label:" United States - West Virginia 4.0 "} ,
{lat: 43.7844397 , lng: -88.7878678 , label:" United States - Wisconsin 4.0 "} ,
{lat: 43.0759678 , lng: -107.2902839 , label:" United States - Wyoming 5.0 "} ,
{lat: -32.522779 , lng: -55.765835 , label:" Uruguay 3.0 "} ,
{lat: 41.377491 , lng: 64.585262 , label:" Uzbekistan 4.0 "} ,
{lat: 6.42375 , lng: -66.58973 , label:" Venezuela 3.0 "} ,
{lat: 14.058324 , lng: 108.277199 , label:" Vietnam 3.0 "} ,
{lat: 15.552727 , lng: 48.516388 , label:" Yemen 3.5 "} ,
{lat: -13.133897 , lng: 27.849332 , label:" Zambia 4.0 "} ,
{lat: -19.015438 , lng: 29.154857 , label:" Zimbabwe 6.0 "} ,